# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Singularity container build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y build-essential libssl-dev uuid-dev libgpgme11-dev squashfs-tools libseccomp-dev ;pkg-config;
         export VERSION=1.11 OS=linux ARCH=amd64 && \
            wget https://dl.google.com/go/go$VERSION.$OS-$ARCH.tar.gz && \
            sudo tar -C /usr/local -xzvf go$VERSION.$OS-$ARCH.tar.gz && \
            rm go$VERSION.$OS-$ARCH.tar.gz;
        echo 'export GOPATH=${HOME}/go' >> ~/.bashrc && \
        echo 'export PATH=/usr/local/go/bin:${PATH}:${GOPATH}/bin' >> ~/.bashrc && \
        source ~/.bashrc;
        go get -u github.com/golang/dep/cmd/dep;
        export VERSION=v3.0.3 # or another tag or branch if you like && \
            cd $GOPATH/src/github.com/sylabs/singularity && \
            git fetch && \
            git checkout $VERSION;
            export VERSION=3.0.3 && # adjust this as necessary \
        mkdir -p $GOPATH/src/github.com/sylabs && \
        cd $GOPATH/src/github.com/sylabs && \
        wget https://github.com/sylabs/singularity/releases/download/v${VERSION}/singularity-${VERSION}.tar.gz && \
        tar -xzf singularity-${VERSION}.tar.gz && \
        cd ./singularity && \
        ./mconfig;
        ./mconfig && \
            make -C ./builddir && \
            sudo make -C ./builddir install;
        ./mconfig --prefix=/opt/singularity
    - name: Install container
      run: |
        cd containers; bash generate.sh

